{"name": "test_a_list", "status": "failed", "statusDetails": {"message": "AssertionError: assert 3 == 10\n  +3\n  -10", "trace": "a_list = [1, 2, 3, 9, 10]\n\n    def test_a_list(a_list):\n>       assert a_list[2] == 10\nE       assert 3 == 10\nE         +3\nE         -10\n\ntest_sample1.py:19: AssertionError"}, "start": 1590298089137, "stop": 1590298089137, "uuid": "4de8771b-95bb-451f-b8bf-4d8a2a0e4383", "historyId": "b5014659583c20830fa026fd4fbf32fc", "testCaseId": "a1f6a4e23ef87db930015d1bca377ac8", "fullName": "200522_fixture.test_sample1#test_a_list", "labels": [{"name": "parentSuite", "value": "200522_fixture"}, {"name": "suite", "value": "test_sample1"}, {"name": "host", "value": "MSI"}, {"name": "thread", "value": "24500-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "200522_fixture.test_sample1"}]}